### ISSUE TITLE
no-treeshake causing inclusion of dead CSS and "phantom" js modules

### ISSUE THREAD

**Issue by antony** [domingues/rollup-plugin-css-chunks#7]
I've been trying to diagnose the root cause of this issue, which has a net result of including way too much unused CSS in a sapper app (from modules which are installed but not used after treeshaking), but also slightly more concerning, the building of empty js modules whose contents have been extracted to the top-level but still exist due to the way we determine if modules are required or not:

https://github.com/sveltejs/sapper/issues/1564

and as @benmccann has helpfully pointed out (a few days, before I actually understood what he was saying!) I've managed to debug down to the following line:

https://github.com/domingues/rollup-plugin-css-chunks/blob/master/index.ts#L90

Switching `no-treeshake` to `false` appears to fix the issue.

So before opening a PR to do this, I guess the important question is, why is it currently set to `no-treeshake`, and will setting it to `false` cause any issues?

**Comment by domingues** [comment]
That configuration was added to support Rollup 2. https://github.com/domingues/rollup-plugin-css-chunks/pull/2/files
Need to check if this is an issue of this plugin or the sapper build.

**Comment by benmccann** [comment]
We had to make that change in Sapper for Rollup 2 support. See https://github.com/rollup/rollup/issues/3655 for full details on that. I didn't test this plugin without that flag, but just had assumed that it would be necessary here as well. Perhaps it's not though based off what you're saying? It could be useful to start a test suite in this repo, so that we can make sure we're handling these various edge cases and don't regress them as we make changes. I'm not really sure the best way to test a Rollup plugin though.

**Comment by domingues** [comment]
Just some extra info. Sapper has `injectImports: true`, that produces (using your repo https://github.com/antony/phantom-modules) some extra CSS files, for example `index-1257813d.css`. This files also desapear when `moduleSideEffects`is `null`.

**Comment by domingues** [comment]
@antony could you please try this commit, I think it fixes the problem?
https://github.com/domingues/rollup-plugin-css-chunks/commit/6f121cc2712b15c6d92a93e59488c88861b347d5
